from dataset_reader import GFF3DatasetReader

filepath='Homo_sapiens.GRCh38.85.gff3.gz'
reader = GFF3DatasetReader()
human_genome = reader.read(filepath)

print(human_genome.get_df().head())
print(human_genome.get_df().shape)
print()
print(type(human_genome))
print(human_genome.get_active_operations())
print()

general_info = human_genome.get_information()
print(general_info.get_df().head(9))
print()
print(type(general_info))
print(general_info.get_active_operations())
print()

sequence_IDs = human_genome.unique_seq_IDs()
print(sequence_IDs.get_df().head())
print(sequence_IDs.get_df().shape)
print()
print(type(sequence_IDs))
print(sequence_IDs.get_active_operations())
print()

same_source = human_genome.same_source()
print(same_source.get_df().head())
print(same_source.get_df().shape)
print()
print(type(same_source))
print(same_source.get_active_operations())
print()

chromosomes = human_genome.get_chromosomes()
print(chromosomes.get_df().head())
print(chromosomes.get_df().shape)
print()
print(type(chromosomes))
print(chromosomes.get_active_operations())
print()

fraction = human_genome.fraction_of_unassembled_seq()
print(fraction.get_df().head())
print(fraction.get_df().shape)
print()
print(type(fraction))
print(fraction.get_active_operations())
print()

subset = human_genome.ensembl_havana()
print(subset.get_df().head())
print(subset.get_df().shape)
print()
print(type(subset))
print(subset.get_active_operations())
print()

gene_names = human_genome.get_gene_names()
print(gene_names.get_df().head())
print(gene_names.get_df().shape)
print()
print(type(gene_names))
print(gene_names.get_active_operations())
print()

types = human_genome.type_of_operations()
print(types.get_df().head())
print(types.get_df().shape)
print()
print(type(types))
print(types.get_active_operations())
print()

entries_for_types = human_genome.entries_for_each_type_of_operation()
print(entries_for_types.get_df().head())
print(entries_for_types.get_df().shape)
print()
print(type(entries_for_types))
print(entries_for_types.get_active_operations())
print()

entries_for_types_ensemblehavana = human_genome.entries_for_each_type_of_operation_ensemblhavana()
print(entries_for_types_ensemblehavana.get_df().head())
print(entries_for_types_ensemblehavana.get_df().shape)
print()
print(type(entries_for_types_ensemblehavana))
print(entries_for_types_ensemblehavana.get_active_operations())
print()

entries_for_types_ensemblehavana = subset.entries_for_each_type_of_operation_ensemblhavana()
print(entries_for_types_ensemblehavana.get_df().head())
print(entries_for_types_ensemblehavana.get_df().shape)
print()
print(type(entries_for_types_ensemblehavana))
print(entries_for_types_ensemblehavana.get_active_operations())
print()